name: autopilot

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - if: |
          contains(github.event.pull_request.labels.*.name, 'area/dependency') &&
          !contains(github.event.pull_request.labels.*.name, 'do-not-merge') &&
          github.actor == 'renovate[bot]'
        uses: hmarr/auto-approve-action@v4
