name: linters

on:
  pull_request:
    branches: [ '*' ]

permissions:
  contents: read

jobs:
  tf-linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
      - run: |
          tofu fmt -check -diff -recursive .

  shell-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@master
