name: linters

on:
  pull_request:
    branches: [ '*' ]

permissions:
  contents: read

jobs:
  tofu-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: opentofu/setup-opentofu@v1
      - run: |
          tofu fmt -check -diff -recursive .

  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: terraform-linters/setup-tflint@v6
      - run: |
          tflint --init
          tflint --recursive

  shell-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ludeeus/action-shellcheck@master
